# -----------------------------
# Configuración de la base de datos PostgreSQL
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/sesiones_bienestar?connectTimeout=10&sslmode=prefer
spring.datasource.username=postgres
spring.datasource.password=Fernandoe01.
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------
# Configuración de JPA / Hibernate
# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -----------------------------
# Opcional: Perfil de Spring Boot
# -----------------------------
spring.profiles.active=default
